### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Art0343** [lexwilliam/Risuto#5]
![Screenshot_20220325-120359](https://user-images.githubusercontent.com/91286865/160067442-baff71e1-2a2e-4f8b-bb33-74d980749b36.png)
I think it will be better if the poster of the anime is in middle of the screen. It looks weird in the very right.
Hide the activity text like completed/10
When scrolling through the information about the anime
![Screenshot_20220325-121000](https://user-images.githubusercontent.com/91286865/160068092-338dbc36-8f1a-44ca-bcd0-e35419f6d881.png)

**Comment by lexwilliam** [comment]
Actually for the anime details, it was inspired by this ui design https://dribbble.com/shots/7902411-Actors-Tracking-App. I choose this design because it looks unique and easy to implement but breaks the material design principal/rule which makes it seem a little bit of. So yeah actually you're right, maybe i will change the design one day.

For the toolbar, originally i want it to make it transition to a normal toolbar when you don't see the poster so it will not interfere with the views like you said. I haven't implement that because haven't learned how to do such animation. So i will implement it in the next patch.

Thank you for the suggestion and the help from the last issue!!!

**Comment by Art0343** [comment]
no problem. Take your time👍

**Comment by Art0343** [comment]
Also @lexwilliam how about making a discord?
You can update in discord whenever you release a new build. Or just share your upcoming plans with the app.

**Comment by lexwilliam** [comment]
I have never make a discord server actually. So maybe i look into it.

**Comment by Art0343** [comment]
Okay but making a discord server helps other users who aren't familiar with github actions.
If you make one don't forget to pin the link on your main page where you added the app preview images/ information etc

**Comment by lexwilliam** [comment]
The toolbar fill in when the anime poster no longer on the screen in 0.8.2-alpha
